// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface AboutFrontpediaFields {}

export interface AboutFrontpedia extends OstDocument<AboutFrontpediaFields> {}

export type AboutFrontpediaField = keyof AboutFrontpedia
