// Generated by Outstatic - do not edit manually
// This file provides typed overloads for Outstatic server functions

import type { CollectionName, CollectionDocument, SingletonName, SingletonDocument, AllDocuments } from './collections'
import type { InspirationFields } from './inspiration'
import type { PeopleFields } from './people'
import type { PostsFields } from './posts'
import type { ResourcesFields } from './resources'
import type { AboutFrontpediaFields } from './_singletons/about-frontpedia'
import type { OutstaticSchema } from 'outstatic'
import type { Query } from 'sift'

/** Fluent API for querying documents */
interface FindAPI<T, P = T> {
  /** Sort results by field(s) */
  sort(sort: { [K in keyof T]?: 1 | -1 } | (keyof T)[] | keyof T): FindAPI<T, P>
  /** Select fields to return (use 'as const' for type narrowing) */
  project<K extends keyof T>(projection: readonly K[]): FindAPI<T, Pick<T, K>>
  project(projection: Record<string, number>): FindAPI<T, Partial<T>>
  /** Skip N results */
  skip(skip: number): FindAPI<T, P>
  /** Limit to N results */
  limit(limit: number): FindAPI<T, P>
  /** Get first result */
  first(): Promise<P | undefined>
  /** Get all results as array */
  toArray(): Promise<P[]>
}

/** Infers the document type from a query's collection property */
type InferDocumentType<Q> =
  Q extends { collection: 'inspiration' } ? OutstaticSchema<InspirationFields> :
  Q extends { collection: 'people' } ? OutstaticSchema<PeopleFields> :
  Q extends { collection: 'posts' } ? OutstaticSchema<PostsFields> :
  Q extends { collection: 'resources' } ? OutstaticSchema<ResourcesFields> :
  OutstaticSchema<AllDocuments>

/** API returned by load() */
interface LoadAPI {
  /** Find inspiration documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<InspirationFields>>(
    query: { collection: 'inspiration' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<InspirationFields>, Pick<OutstaticSchema<InspirationFields>, K>>

  /** Find inspiration documents */
  find(
    query: { collection: 'inspiration' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<InspirationFields>>

  /** Find inspiration documents */
  find(
    query: { collection: 'inspiration' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<InspirationFields>>

  /** Find people documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<PeopleFields>>(
    query: { collection: 'people' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<PeopleFields>, Pick<OutstaticSchema<PeopleFields>, K>>

  /** Find people documents */
  find(
    query: { collection: 'people' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<PeopleFields>>

  /** Find people documents */
  find(
    query: { collection: 'people' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<PeopleFields>>

  /** Find posts documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<PostsFields>>(
    query: { collection: 'posts' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<PostsFields>, Pick<OutstaticSchema<PostsFields>, K>>

  /** Find posts documents */
  find(
    query: { collection: 'posts' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<PostsFields>>

  /** Find posts documents */
  find(
    query: { collection: 'posts' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<PostsFields>>

  /** Find resources documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<ResourcesFields>>(
    query: { collection: 'resources' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<ResourcesFields>, Pick<OutstaticSchema<ResourcesFields>, K>>

  /** Find resources documents */
  find(
    query: { collection: 'resources' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<ResourcesFields>>

  /** Find resources documents */
  find(
    query: { collection: 'resources' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<ResourcesFields>>

  /** Find documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<AllDocuments>>(
    query: Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<AllDocuments>, Pick<OutstaticSchema<AllDocuments>, K>>

  /** Find documents matching a query */
  find(
    query: Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<AllDocuments>>

  /** Find documents matching a query */
  find(
    query: Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<AllDocuments>>

  /** Find documents with explicit return type */
  find<T>(
    query: Record<string, unknown>,
    projection?: string[] | { [key: string]: number }
  ): FindAPI<T>
}

declare module 'outstatic/server' {
  /**
   * Get all documents from a collection
   * @param collection - The collection name
   * @param fields - Optional array of fields to include (use 'as const' for type narrowing)
   */
  export function getDocuments<
    C extends CollectionName,
    F extends readonly (keyof CollectionDocument<C>)[] | undefined = undefined
  >(
    collection: C,
    fields?: F
  ): F extends readonly (keyof CollectionDocument<C>)[]
    ? Pick<CollectionDocument<C>, F[number]>[]
    : CollectionDocument<C>[]

  /**
   * Get a single document by its slug
   * @param collection - The collection name
   * @param slug - The document slug
   * @param fields - Optional array of fields to include (use 'as const' for type narrowing)
   */
  export function getDocumentBySlug<
    C extends CollectionName,
    F extends readonly (keyof CollectionDocument<C>)[] | undefined = undefined
  >(
    collection: C,
    slug: string,
    fields?: F
  ): F extends readonly (keyof CollectionDocument<C>)[]
    ? Pick<CollectionDocument<C>, F[number]> | null
    : CollectionDocument<C> | null

  /**
   * Get all document slugs from a collection
   * @param collection - The collection name
   */
  export function getDocumentSlugs(collection: CollectionName): string[]

  /**
   * Get document paths for static generation
   * @param collection - The collection name
   */
  export function getDocumentPaths(collection: CollectionName): { params: { slug: string } }[]

  /**
   * Get a singleton by its slug
   * @param slug - The singleton slug
   * @param fields - Optional array of fields to include (use 'as const' for type narrowing)
   */
  export function getSingletonBySlug<
    S extends SingletonName,
    F extends readonly (keyof SingletonDocument<S>)[] | undefined = undefined
  >(
    slug: S,
    fields?: F
  ): F extends readonly (keyof SingletonDocument<S>)[]
    ? Pick<SingletonDocument<S>, F[number]> | null
    : SingletonDocument<S> | null

  /**
   * Get all singleton slugs
   */
  export function getSingletonSlugs(): SingletonName[]

  /**
   * Load the metadata database for advanced querying
   * @returns LoadAPI with typed find method that narrows based on collection query
   */
  export function load(): Promise<LoadAPI>
}
