// Generated by Outstatic - do not edit manually

import type { Inspiration, InspirationFields } from './inspiration'
import type { People, PeopleFields } from './people'
import type { Posts, PostsFields } from './posts'
import type { Resources, ResourcesFields } from './resources'
import type { AboutFrontpedia, AboutFrontpediaFields } from './_singletons/about-frontpedia'

export type CollectionName = 'inspiration' | 'people' | 'posts' | 'resources'

export type SingletonName = 'about-frontpedia'

export interface Collections {
  'inspiration': Inspiration
  'people': People
  'posts': Posts
  'resources': Resources
}

export interface Singletons {
  'about-frontpedia': AboutFrontpedia
}

export type CollectionDocument<C extends CollectionName> = Collections[C]
export type SingletonDocument<S extends SingletonName> = Singletons[S]

/** Union of all document field types for use with load() */
export type AllDocuments = InspirationFields | PeopleFields | PostsFields | ResourcesFields | AboutFrontpediaFields
