// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface InspirationFields {
  /** Type in the website URL */
  websiteUrl: string
  /** Use video as document cover */
  videoCover?: string
  description?: string
  coverImage?: string
  tags?: Array<{ label: string; value: 'agency' | 'threeJs' | 'blender' | 'gsap' | 'portfolio' | 'webflow' | 'cms' | 'markdown' }>
}

export interface Inspiration extends OstDocument<InspirationFields> {}

export type InspirationField = keyof Inspiration
