// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface PeopleFields {
  /** Link to portfolio, etc... */
  websiteUrl?: string
  twitter?: string
}

export interface People extends OstDocument<PeopleFields> {}

export type PeopleField = keyof People
