// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface ResourcesFields {
  websiteUrl?: string
  videoCover?: string
  coverImage?: string
  description?: string
  category?: Array<{ label: string; value: 'webGl' | 'ai' }>
}

export interface Resources extends OstDocument<ResourcesFields> {}

export type ResourcesField = keyof Resources
